Repository RAF-SI-2023/Banka-2-Infrastructure, pull requests merged in 2024-05, with the labels that each got.

#2 Ispravka za frontend
  .env
  images/Frontend.Dockerfile
Labels: size/XS, lgtm, approved

#4 Ispravljena imena Dockerfile-ova
  docker-compose.yml
  images/bank-service.Dockerfile
  images/frontend.Dockerfile
  images/iam-service.Dockerfile
  images/notification-service.Dockerfile
  images/otc-service.Dockerfile
  images/stock-service.Dockerfile
Labels: lgtm, approved, size/M

#5 Update docker-compose.yml
  docker-compose.yml
Labels: lgtm, approved, size/S

#9 Kubernetes
  README.md
  kubernetes/bank-service.yaml
  kubernetes/frontend.yaml
  kubernetes/iam-service.yaml
  kubernetes/ingress.yaml
  kubernetes/namespaces.yaml
  kubernetes/notification-service.yaml
  kubernetes/otc-service.yaml
  kubernetes/postgres.yaml
  kubernetes/redis.yaml
  kubernetes/stock-service.yaml
Labels: lgtm, approved, size/XL

#10 ENVS
  .gitignore
  .idea/.gitignore
  .idea/Banka-2-Infrastructure.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
  kubernetes/bank-service.yaml
  kubernetes/iam-service.yaml
  kubernetes/otc-service.yaml
Labels: lgtm, approved, size/M

#11 Delete .idea directory
  .idea/.gitignore
  .idea/Banka-2-Infrastructure.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
Labels: lgtm, approved, size/M

#13 Delete .idea directory
  .idea/.gitignore
  .idea/Banka-2-Infrastructure.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
Labels: lgtm, approved, size/M

#14 .idea removed
  helm/banka-2-backend/templates/bank-service.yaml
  helm/banka-2-backend/templates/iam-service.yaml
  helm/banka-2-backend/templates/otc-service.yaml
  kubernetes/bank-service.yaml
  kubernetes/iam-service.yaml
  kubernetes/otc-service.yaml
Labels: lgtm, approved, size/M
