Repository RAF-SI-2023/Banka-2-Infrastructure, pull requests merged in 2024-06, with the labels that each got.

#15 Deleted unnecessary envs
  .prow/build.yaml
  helm/.gitignore
  kubernetes/bank-service.yaml
  kubernetes/frontend.yaml
  kubernetes/iam-service.yaml
  kubernetes/ingress.yaml
  kubernetes/namespaces.yaml
  kubernetes/notification-service.yaml
  kubernetes/otc-service.yaml
  kubernetes/postgres.yaml
  kubernetes/redis.yaml
  kubernetes/stock-service.yaml
Labels: lgtm, approved, size/XL

#16 Build yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#17 Optimizacija resursa
  helm/banka-2-backend/templates/bank-service.yaml
  helm/banka-2-backend/templates/iam-service.yaml
  helm/banka-2-backend/templates/notification-service.yaml
  helm/banka-2-backend/templates/otc-service.yaml
  helm/banka-2-backend/templates/redis.yaml
  helm/banka-2-backend/templates/stock-service.yaml
  helm/banka-2-frontend/templates/frontend.yaml
Labels: approved, size/S

#19 Update frontend.Dockerfile
  images/frontend.Dockerfile
Labels: lgtm, approved, size/S

#20 Namespaces
  helm/banka-2-frontend/Chart.yaml
  helm/banka-2-frontend/templates/frontend.yaml
  helm/banka-2-frontend/values.yaml
Labels: lgtm, approved
